// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA70mePSRCqpaQcidixTg7l4x-9EWBNaqk',
    appId: '1:1072410230729:web:995bc28207ea7ecfc3f218',
    messagingSenderId: '1072410230729',
    projectId: 'film-sphere',
    authDomain: 'film-sphere.firebaseapp.com',
    storageBucket: 'film-sphere.firebasestorage.app',
    measurementId: 'G-R0J3RP5SB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-wFL_ilxiRGLLuaOASLvmcp2YzwV2MI4',
    appId: '1:1072410230729:android:06aa5836220b14b5c3f218',
    messagingSenderId: '1072410230729',
    projectId: 'film-sphere',
    storageBucket: 'film-sphere.firebasestorage.app',
  );

}